### ISSUE TITLE
[Question] Is the latest version compatible with all Minecraft versions?

### ISSUE THREAD

**Issue by c0wg0d** [mirolm/zPermissions#2]
Hi,

Glad to see you are still maintaining this plugin.  I have a mix of servers from 1.8 to 1.15.2.  Is the latest dev build compatible with the older versions, or is it for 1.13+ only?  Also do you think the latest version on Jenkins is stable enough for production or should I wait for a more official release?

Thanks for keeping this plugin up to date!

**Comment by mirolm** [comment]
Hey,

It will work with bukkit 1.13 and later because of the api-version that is set. If older servers do not check the api it will work with them too.

The version in Jenkins is the same as in latest one in releases actually most of times. As for if it is ready for production i never had a chance to test it to something bigger than my small home server.   I try to do non breaking changes to original code to keep it working. Other refactorings are more like what IntelliJ proposes. All in all i try to keep it working because i really like this plugin. There are no official releases - i just commit code from time to time and try to fix/refactor if i see something.

Glad you like it and thank you too.
